export const NATIONALITY = {
    AU : "AU",
    BR : "BR",
    CA : "CA",
    CH : "CH",
    DE : "DE",
    DK : "DK",
    ES : "ES",
    FI : "FI",
    FR : "FR",
    GB : "GB",
    IE : "IE",
    IR : "IR",
    NO : "NO",
    NL : "NL",
    NZ : "NZ",
    TR : "TR",
    US : "US",
}
export const NATIONALITYHumanName = {
    [NATIONALITY.AU]: 'Australian',
    [NATIONALITY.BR]: 'Brazilian',
    [NATIONALITY.CA]: "Canadian",
    [NATIONALITY.CH]: 'Chinese',
    [NATIONALITY.DE]: 'German',
    [NATIONALITY.ES]: 'Spanish',
    [NATIONALITY.FI]: 'Finnish',
    [NATIONALITY.FR]: 'French',
    [NATIONALITY.GB]: 'British',
    [NATIONALITY.IE]: 'Irish',
    [NATIONALITY.IR]: 'Iranian',
    [NATIONALITY.NO]: 'Norwegian',
    [NATIONALITY.NL]: 'Dutch',
    [NATIONALITY.NZ]: 'New Zealand',
    [NATIONALITY.TR]: 'Turkish',
    [NATIONALITY.US]: 'American',
}